[project]
name = "transformer-segmenter"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.12.0"
dependencies = [
    "torch>=2.8.0",
    "numpy>=2.3.3",
    "ray[tune,train]",
    "tqdm",
    "matplotlib>=3.10.7",
    "hyperopt==0.2.5",

    "evaluation-utils",
    "annotated-corpus-dataset",
]
