[project]
name = "from-scratch-tagger"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.12.0"
dependencies = [
    "torch>=2.8.0",
    "numpy>=2.3.3",
    "scikit-learn>=1.7.2",
    "ray[tune,train]",

    "evaluation-utils",
    "annotated-corpus-dataset",
]
