[project]
name = "annotated-corpus-dataset"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
        "torch>=2.8.0",
        "numpy>=2.3.3",
        "tqdm>=4.67.1",
]
